import {
  Baby,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Cake,
  Camera,
  Car,
  Cat,
  Church,
  Cigarette,
  Coffee,
  CreditCard,
  Cross,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Fish,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HandHeart,
  HeartPulse,
  Home,
  Landmark,
  Leaf,
  Music,
  Palette,
  PawPrint,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Plug,
  Receipt,
  Repeat,
  Scissors,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Stethoscope,
  Sun,
  Tent,
  Ticket,
  Train,
  Trash2,
  TreePine,
  Trophy,
  Umbrella,
  UtensilsCrossed,
  Wallet,
  Waves,
  Wifi,
  Wine,
  Wrench,
  type LucideIcon,
} from "lucide-react";

// The full set of icons a bucket can carry — the keyword rules below map
// into these keys, and the AI picker (suggestBucketIcons, src/lib/ai.ts) is
// constrained to this exact key list so it can never invent one we can't
// render. Keep keys short and lowercase.
export const BUCKET_ICONS = {
  utensils: UtensilsCrossed,
  pizza: Pizza,
  cake: Cake,
  coffee: Coffee,
  wine: Wine,
  cart: ShoppingCart,
  bag: ShoppingBag,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  fuel: Fuel,
  car: Car,
  bus: Bus,
  bike: Bike,
  plane: Plane,
  train: Train,
  health: HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  cross: Cross,
  dumbbell: Dumbbell,
  film: Film,
  music: Music,
  game: Gamepad2,
  camera: Camera,
  palette: Palette,
  ticket: Ticket,
  book: BookOpen,
  repeat: Repeat,
  phone: Smartphone,
  wifi: Wifi,
  plug: Plug,
  droplet: Droplet,
  flame: Flame,
  trash: Trash2,
  trophy: Trophy,
  baby: Baby,
  school: GraduationCap,
  pet: PawPrint,
  dog: Dog,
  cat: Cat,
  fish: Fish,
  gift: Gift,
  home: Home,
  wrench: Wrench,
  hammer: Hammer,
  leaf: Leaf,
  sprout: Sprout,
  tree: TreePine,
  tent: Tent,
  waves: Waves,
  snowflake: Snowflake,
  sun: Sun,
  umbrella: Umbrella,
  church: Church,
  charity: HandHeart,
  briefcase: Briefcase,
  bank: Landmark,
  piggybank: PiggyBank,
  card: CreditCard,
  cigarette: Cigarette,
  receipt: Receipt,
  wallet: Wallet,
} satisfies Record<string, LucideIcon>;

export type BucketIconKey = keyof typeof BUCKET_ICONS;

export const BUCKET_ICON_KEYS = Object.keys(BUCKET_ICONS) as BucketIconKey[];

// Ordered keyword -> icon key lookup. First match wins, so put more specific
// keywords first (e.g. "dining" before a generic "food").
const RULES: [RegExp, BucketIconKey][] = [
  [/dining|restaurant|takeout|eat/i, "utensils"],
  [/coffee|cafe/i, "coffee"],
  [/grocer/i, "cart"],
  [/clothing|apparel|wardrobe/i, "shirt"],
  [/beauty|salon|hair|nails/i, "scissors"],
  [/retail|shopping|amazon/i, "bag"],
  [/fuel|gas\b/i, "fuel"],
  [/car|auto|vehicle/i, "car"],
  [/transit|bus|subway|rideshare|uber|lyft/i, "bus"],
  [/travel|flight|vacation|trip/i, "plane"],
  [/health|medical|doctor|pharmacy/i, "health"],
  [/gym|fitness|workout/i, "dumbbell"],
  [/movie|entertainment|streaming|film/i, "film"],
  [/music|concert|spotify/i, "music"],
  [/game|gaming|xbox|playstation|steam/i, "game"],
  [/subscription/i, "repeat"],
  [/phone|cell/i, "phone"],
  [/internet|wifi|cable/i, "wifi"],
  [/electric|power\b|utilit/i, "plug"],
  [/water|sewer/i, "droplet"],
  [/kid|activit|dance|sport|basketball|soccer|tumbl/i, "trophy"],
  [/baby|childcare|daycare/i, "baby"],
  [/school|tuition|education/i, "school"],
  [/pet|dog|cat|vet/i, "pet"],
  [/gift|present/i, "gift"],
  [/garden|lawn|yard|landscap/i, "leaf"],
  [/church|tithe|faith/i, "church"],
  [/charit|donation|giving/i, "charity"],
  [/home ?improvement|repair|maintenance|hardware/i, "wrench"],
  [/savings|emergency fund/i, "piggybank"],
  [/mortgage|rent|housing|home/i, "home"],
  [/bill|one-?off/i, "receipt"],
];

// The keyword key for a bucket name, or null when nothing matches (the
// signal ensureBucketIcons uses to decide a bucket needs an AI pick).
export function keywordIconKey(name: string): BucketIconKey | null {
  for (const [pattern, key] of RULES) {
    if (pattern.test(name)) return key;
  }
  return null;
}

function iconFromKey(key: string | null | undefined): LucideIcon | null {
  return key && key in BUCKET_ICONS ? BUCKET_ICONS[key as BucketIconKey] : null;
}

// Final render resolution: the stored AI pick wins, then the live keyword
// rules, then a plain Wallet so there's always something to draw.
export function bucketIconComponent(bucket: { name: string; icon?: string | null }): LucideIcon {
  return iconFromKey(bucket.icon) ?? iconFromKey(keywordIconKey(bucket.name)) ?? Wallet;
}
